# Site
name: "Hackering Pro Publications"
title: "hackering.pro"
description: "A Junior Publication for Cyber Security and InfoSec."
meta_description: "A Junior Publication for Cyber Security and InfoSec."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: 'UA-136538341-1'
disqus: 'hackeringpro'
mailchimp-list: 'https://sherlock-security.us20.list-manage.com/subscribe/post?u=d19545474f9d159259f439c8e&amp;id=c888c445e5'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  dan:
    name: Dan
    display_name: "_Dan_ (SherlockSec)"
    email: dan@sherlock-security.com
    web: https://sherlock-security.com
    twitter: https://twitter.com/sherlocksec
    description: "Computer Security Student. Does something to do with Hackering. Might be a pro or something"

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
